class AppWords {
  static const Map<String, Map<String, String>> translations = {
    'English': {
      'Profile': 'Profile',
      'Name': 'Name',
      'Email': 'Email',
      'Change Email': 'Change Email',
      'Change Password': 'Change Password',
      'Change Language': 'Change Language',
      'Log Out': 'Log Out',
      'Cancel': 'Cancel',
      'Save': 'Save',
      'Edit Name': 'Edit Name',
      'Edit Email': 'Edit Email',
      'Enter new Name': 'Enter new Name',
      'Enter new Email': 'Enter new Email',
      'Language': 'Language',
      'English': 'English',
      'Arabic': 'Arabic',
      'Please fill all fields': 'Please fill all fields',
      'Password updated successfully!': 'Password updated successfully!',
      'An error occurred': 'An error occurred',
      'Current password is incorrect': 'Current password is incorrect',
      'The new password is too weak': 'The new password is too weak',
      'Current Password': 'Current Password',
      'New Password': 'New Password',
      'Update Password': 'Update Password',
      'No description provided.': 'No description provided.',
      'Created at ': 'Created at ',
      'N/A': 'N/A',
    },
    'Arabic': {
      'Profile': 'الصفحة الشخصية',
      'Name': 'الاسم',
      'Email': 'البريد الإلكتروني',
      'Change Email': 'تغيير البريد الإلكتروني',
      'Change Password': 'تغيير كلمة المرور',
      'Change Language': 'تغيير اللغة',
      'Log Out': 'تسجيل الخروج',
      'Cancel': 'إلغاء',
      'Save': 'حفظ',
      'Edit Name': 'تعديل الاسم',
      'Edit Email': 'تعديل البريد',
      'Enter new Name': 'أدخل الاسم الجديد',
      'Enter new Email': 'أدخل البريد الجديد',
      'Language': 'اللغة',
      'English': 'الإنجليزية',
      'Arabic': 'العربية',
      'Please fill all fields': 'يرجى ملء جميع الحقول',
      'Password updated successfully!': 'تم تحديث كلمة المرور بنجاح!',
      'An error occurred': 'حدث خطأ ما',
      'Current password is incorrect': 'كلمة المرور الحالية غير صحيحة',
      'The new password is too weak': 'كلمة المرور الجديدة ضعيفة جداً',
      'Current Password': 'كلمة المرور الحالية',
      'New Password': 'كلمة المرور الجديدة',
      'Update Password': 'تحديث كلمة المرور',
      'No description provided.': 'لا يوجد وصف.',
      'Created at ': 'تم الإنشاء في ',
      'N/A': 'غير متوفر',
    }
  };

  static String tr(String word, String language) {
    return translations[language]?[word] ?? word;
  }
}