// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4jmcXmIsp6IVxgJvQ7GI39FOnHH2umFw',
    appId: '1:1029600901193:web:2cea0e6886ba50cb3b2798',
    messagingSenderId: '1029600901193',
    projectId: 'to-do-b1fb8',
    authDomain: 'to-do-b1fb8.firebaseapp.com',
    storageBucket: 'to-do-b1fb8.firebasestorage.app',
    measurementId: 'G-FN7J5P10Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfb8rNPAYLMnRPrW4e9o2cU3mypOnhDY',
    appId: '1:1029600901193:android:6e513dc8d6b2204b3b2798',
    messagingSenderId: '1029600901193',
    projectId: 'to-do-b1fb8',
    storageBucket: 'to-do-b1fb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxeJ8czzM2XOjZbgYnZbdtTB26M890Eqc',
    appId: '1:1029600901193:ios:952d2dc4fbbe69ff3b2798',
    messagingSenderId: '1029600901193',
    projectId: 'to-do-b1fb8',
    storageBucket: 'to-do-b1fb8.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

}