class AppWords {
  static const Map<String, Map<String, String>> translations = {
    'English': {
      'Profile': 'Profile',
      'Name': 'Name',
      'Email': 'Email',
      'Change Email': 'Change Email',
      'Change Password': 'Change Password',
      'Change Language': 'Change Language',
      'Log Out': 'Log Out',
      'Cancel': 'Cancel',
      'Save': 'Save',
      'Edit Name': 'Edit Name',
      'Edit Email': 'Edit Email',
      'Enter new Name': 'Enter new Name',
      'Enter new Email': 'Enter new Email',
      'Language': 'Language',
      'English': 'English',
      'Arabic': 'Arabic',
      'Please fill all fields': 'Please fill all fields',
      'Password updated successfully!': 'Password updated successfully!',
      'An error occurred': 'An error occurred',
      'Current password is incorrect': 'Current password is incorrect',
      'The new password is too weak': 'The new password is too weak',
      'Current Password': 'Current Password',
      'New Password': 'New Password',
      'Update Password': 'Update Password',
      'No description provided.': 'No description provided.',
      'Created at ': 'Created at ',
      'N/A': 'N/A',
      'Sign In': 'Sign In',
      'Password': 'Password',
      'Forgot Password?': 'Forgot Password?',
      'Don\'t have an account? Sign up': 'Don\'t have an account? Sign up',
      'No user found for that email.': 'No user found for that email.',
      'Wrong password provided.': 'Wrong password provided.',
      'Sign Up': 'Sign Up',
      'Full Name': 'Full Name',
      'Confirm Password': 'Confirm Password',
      'All fields are required': 'All fields are required',
      'The password does not match': 'The password does not match',
      'Have an account? Sign in': 'Have an account? Sign in',
      'Title': 'Title',
      'Description': 'Description',
      'Deadline (Optional)': 'Deadline (Optional)',
      'Add Image (Optional)': 'Add Image (Optional)',
      'ADD TODO': 'ADD TODO',
      'User Name': 'User Name',
      'user@example.com': 'user@example.com',
      'Pending': 'Pending',
      'Completed': 'Completed',
      'Deadline': 'Deadline',
      'Image': 'Image',
      'Dark Mode': 'Dark Mode',
      'Choose Theme': 'Choose Theme',
    },
    'Arabic': {
      'Profile': 'الصفحة الشخصية',
      'Name': 'الاسم',
      'Email': 'البريد الإلكتروني',
      'Change Email': 'تغيير البريد الإلكتروني',
      'Change Password': 'تغيير كلمة المرور',
      'Change Language': 'تغيير اللغة',
      'Log Out': 'تسجيل الخروج',
      'Cancel': 'إلغاء',
      'Save': 'حفظ',
      'Edit Name': 'تعديل الاسم',
      'Edit Email': 'تعديل البريد',
      'Enter new Name': 'أدخل الاسم الجديد',
      'Enter new Email': 'أدخل البريد الجديد',
      'Language': 'اللغة',
      'English': 'الإنجليزية',
      'Arabic': 'العربية',
      'Please fill all fields': 'يرجى ملء جميع الحقول',
      'Password updated successfully!': 'تم تحديث كلمة المرور بنجاح!',
      'An error occurred': 'حدث خطأ ما',
      'Current password is incorrect': 'كلمة المرور الحالية غير صحيحة',
      'The new password is too weak': 'كلمة المرور الجديدة ضعيفة جداً',
      'Current Password': 'كلمة المرور الحالية',
      'New Password': 'كلمة المرور الجديدة',
      'Update Password': 'تحديث كلمة المرور',
      'No description provided.': 'لا يوجد وصف.',
      'Created at ': 'تم الإنشاء في ',
      'N/A': 'غير متوفر',
      'Sign In': 'تسجيل الدخول',
      'Password': 'كلمة المرور',
      'Forgot Password?': 'هل نسيت كلمة المرور؟',
      'Don\'t have an account? Sign up': 'ليس لديك حساب؟ إنشاء حساب',
      'No user found for that email.': 'لا يوجد مستخدم بهذا البريد.',
      'Wrong password provided.': 'كلمة المرور غير صحيحة.',
      'Sign Up': 'إنشاء حساب',
      'Full Name': 'الاسم الكامل',
      'Confirm Password': 'تأكيد كلمة المرور',
      'All fields are required': 'جميع الحقول مطلوبة',
      'The password does not match': 'كلمات المرور غير متطابقة',
      'Have an account? Sign in': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'Title': 'العنوان',
      'Description': 'الوصف',
      'Deadline (Optional)': 'تاريخ الانتهاء (اختياري)',
      'Add Image (Optional)': 'إضافة صورة (اختياري)',
      'ADD TODO': 'إضافة المهمة',
      'User Name': 'اسم المستخدم',
      'user@example.com': 'البريد الإلكتروني',
      'Pending': 'قيد الانتظار',
      'Completed': 'مكتمل',
      'Deadline': 'تاريخ الانتهاء',
      'Image': 'الصورة',
      'Dark Mode': 'الوضع الليلي',
      'Choose Theme': 'اختر اللون',
    }
  };

  static String tr(String word, String language) {
    return translations[language]?[word] ?? word;
  }
}